config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
 devise_for :users, :controllers => { registrations: 'my_registrations' }

 devise_scope :user do
 	   get '/users/restore', :to => 'my_registrations#restore'
 end

 resources :products
 resources :orders
 resources :charges
 
  root 'welcomes#index'

  resources :products
  resources :orders
  resources :comments

  get 'location' => 'pages#location'
  get 'our_story' => 'pages#our_story'
  get 'the_owner' => 'pages#the_owner'
  get 'coffeebean' => 'pages#coffeebean'
  get 'press' => 'pages#press'
  get 'gallery' => 'pages#gallery'
end

app/controllers/my_registrations_controller.rb
class MyRegistrationsController < Devise::RegistrationsController

  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed
    yield resource if block_given?
    redirect_to '/'
  end

  def create
    build_resource(sign_up_params)
    email_input = User.find_by(email: resource.email)
    if email_input != nil and email_input.is_deleted = true
      cookies['email'] = {
        :value => email_input.email,
        :expires => 1.year.from_now
      }
      flash[:notice] = "Hi there, seems like you deleted your account in the past. Please restore your account below or sign-up with a different email address." 
      super
    else
      super
    end 
  end

  def restore
    User.restore_user(cookies[:email])
    redirect_to new_user_session_path
  end 

  

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone_number_mobile, :phone_number_office, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone_number_mobile, :phone_number_office, :password, :password_confirmation, :current_password)
  end
end

app/helpers/my_registrations_helper.rb
module MyRegistrationsHelper
end

app/views/my_registrations/edit.html.erb
<div class="content-lg container-fluid p-0 section-seperator">
  <div class="row two-col">
    <div class="col-md-6">
      <%= image_tag( "edit.jpg", class: "left-img", alt: "Change Password Page")%> 
    </div>
    <div class="col-md-6 right-col">
      <h2>Edit <%= resource_name.to_s.humanize %></h2>

      <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
      <%= devise_error_messages! %>

      <div class="field">
        <%= f.label :first_name %><br />
        <%= f.text_field :first_name, autofocus: true, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :last_name %><br />
        <%= f.text_field :last_name, autofocus: true, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
      </div>

      <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
      <% end %>

      <div class="field">
        <%= f.label :phone_number_mobile %><br />
        <%= f.telephone_field :phone_number_mobile, autofocus: true, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :password %> <em>(leave blank if you don't want to change it)</em><br />
        <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
        <% if @minimum_password_length %>
        <em><%= @minimum_password_length %> characters minimum</em>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :current_password %> <em>(we need your current password to confirm your changes)</em><br />
        <%= f.password_field :current_password, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Update", class: "btn btn-theme btn-theme-sm btn-base-bg text-uppercase" %>
      </div>
      <% end %>
<br>
      <h2>Cancel my account</h2>
      <p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-theme btn-theme-sm btn-base-bg text-uppercase" %></p>
      
      <%= link_to "Back", :back %>
    </div>
  </div>
</div>

app/views/my_registrations/new.html.erb
<div class="content-lg container-fluid p-0">
  <div class="row two-col">
    <div class="col-md-6">
      <%= image_tag( "login.jpg", class: "left-img", alt: "Sign Up Page")%>
    </div>
    <div class="col-md-6 right-col">
      <h2>Sign up</h2>

      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
        <%= link_to "Restore", users_restore_path %>
      <% else %>
        <%= devise_error_messages! %>
      <% end %>

      <div class="field">
        <%= f.label :first_name %><br />
        <%= f.text_field :first_name, autofocus: true, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :last_name %><br />
        <%= f.text_field :last_name, autofocus: true, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :phone_number_mobile %><br />
        <%= f.telephone_field :phone_number_mobile, autofocus: true, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Sign up", class: "btn btn-theme btn-theme-sm btn-base-bg text-uppercase" %>
      </div>
      <% end %>

      <%= render "devise/shared/links" %>
    </div>
  </div>
</div>
<div class="section-seperator"></div>