config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
 devise_for :users, :controllers => { registrations: 'my_registrations' }

 devise_scope :user do
 	   get '/users/restore', :to => 'my_registrations#restore'
 end

 resources :products
 resources :orders
 resources :charges
 
  root 'welcomes#index'

  resources :products
  resources :orders
  resources :comments

  get 'location' => 'pages#location'
  get 'our_story' => 'pages#our_story'
  get 'the_owner' => 'pages#the_owner'
  get 'coffeebean' => 'pages#coffeebean'
  get 'press' => 'pages#press'
  get 'gallery' => 'pages#gallery'
end

app/models/product.rb
class Product < ApplicationRecord
      has_many :order
      has_and_belongs_to_many :variations
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
      def index
            @products = Product.where.not(category: "Addons")
      end
    
      def show
            @product = Product.find(params[:id])
      end
    
      def new
      end
    
      def edit
            @product = Product.find(params[:id])
      end
    
      def create
            @product = Product.new(product_params)

            @product.save
            redirect_to @product
      end
    
      def update
            @product = Product.find(params[:id])

            @product.update(product_params)
            redirect_to @product
      end
    
      def destroy
            @product = Product.find(params[:id])

            @product.update(is_deleted: true)
            redirect_to products_path
      end

      private
            def product_params
                  params.require(:product).permit(:name, :price, :description, :img, :is_deleted, :is_available)
            end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= form_with(model: @product, local: true) do |form| %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
    <p>
    <%= form.label :img %><br>
    <%= form.text_field :img %>
  </p>
  <p>
    <%= form.label :is_available %><br>
    <%= form.check_box :is_available %>
  </p>

  <p>
    <%= form.submit %>
  </p>


<% end %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="jumbotron-pdt jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Menu</h1>
    <%# <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p> %>
  </div>
</div>

<div id="productsContainer" class="container">
  <div class="row">
  <% @products.each do |product| %>
    <div class="col-sm-6 col-md-4 col-lg-3 mt-4">
      <div class="card productCard" id="<%= product.sku %>">
        <img class="card-img-top" src="<%= product.img %>">
        <div class="card-block deepProductCard">
          <h5 class="text-bold"><%= product.name %></h5>
          <h6 class="font-italic"><%= product.description %></h6>
          <% if product.variations.any? %>
            <% product.variations.each do |variation| %>
              <input type="checkbox" name="variation" value="<%= variation.sku %>"> <%= variation.name%><br>
            <% end %>
            <br>
          <% end %>
          <h6 class="font-italic"><%= number_to_currency(product.price) %></h6>
          <% if current_user == nil %>
            <a class="btn btn-success" href="/users/sign_in">Add to Cart</a>
          <% else %>
            <a class="btn btn-success addToCart" data-productsku="<%= product.sku %>">Add to Cart</a>
          <% end %>
          <% if current_user != nil && current_user.is_admin == true %>
            <br>
            <%= link_to 'Show', product_path(product), :class => "btn btn-sm btn-info"%>
            <%= link_to 'Edit', edit_product_path(product), :class => "btn btn-sm btn-warning"%>
            <%= link_to 'Delete', product_path(product),
              method: :delete,
              data: { confirm: 'Are you sure?' }, :class => "btn btn-sm btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>

  <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>Create a new product</h1>

<%= form_with scope: :product, url: products_path, local: true do |form| %>
<%= form.hidden_field :is_deleted, :value => false %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
    <p>
    <%= form.label :img %><br>
    <%= form.text_field :img %>
  </p>
  <p>
    <%= form.label :is_available %><br>
    <%= form.check_box :is_available %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image Url:</strong>
  <%= @product.img %>
</p>

<p>
  <strong>Is it available on the site? :</strong>
  <%= @product.is_available %>
</p>

<p>
  <strong>Has it been deleted? : </strong>
  <%= @product.is_deleted %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %>
<%= link_to 'Back', products_path %>