config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
 devise_for :users, :controllers => { registrations: 'my_registrations' }

 devise_scope :user do
 	   get '/users/restore', :to => 'my_registrations#restore'
 end

 resources :products
 resources :orders
 resources :charges
 
  root 'welcomes#index'

  resources :products
  resources :orders
  resources :comments

  get 'location' => 'pages#location'
  get 'our_story' => 'pages#our_story'
  get 'the_owner' => 'pages#the_owner'
  get 'coffeebean' => 'pages#coffeebean'
  get 'press' => 'pages#press'
  get 'gallery' => 'pages#gallery'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">


  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet" type="text/css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css" rel="stylesheet" type="text/css">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application' %>
 

  <%# Favicon %>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Crown Coffee</title>

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-default navbar-dark">
  <div class="container">
    <%# <div> %>
      <a class="navbar-brand" href="/">
        <%= image_tag( "logo.png", class: "logo-img", alt: "Crown Coffee")%>
      </a>
    <%# </div> %>
    <%# <div> %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <%# <div> %>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">          
      <ul class="navbar-nav navbar-right ml-auto">
        <li class="dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About</a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="/our_story">Our Story</a>
            <a class="dropdown-item" href="/the_owner">The Owner</a>
            <a class="dropdown-item" href="/coffeebean">Coffeebeans</a>            
            <a class="dropdown-item" href="/press">Press</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/products">Menu</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/orders">Cart</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/location">Locations</a>
        </li>
        <% if current_user == nil %>                
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_in">Login/Register</a>
          </li>
        <% else %>
          <li class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.first_name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu">
              <a class="dropdown-item" href="/users/edit">Edit Profile</a>
              <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, :class => "dropdown-item" %>
            </div>
          </li>
        <%end %>
      </ul>
    </div>
  </div>
</nav>

  <%= yield %>

  <%# FOOTER %>
  <footer class="footer">
    <!-- Links -->
    <div class="footer-seperator">
      <div class="content-lg container">
        <div class="row">
          <div class="col-sm-3 sm-margin-b-50">
            <h3>Site Map</h3>
            <!-- List -->
            <ul class="list-unstyled footer-list">
              <li class="footer-list-item"><a class="footer-list-link" href="/">Home</a></li>
              <li class="footer-list-item dropright"><a class="footer-list-link dropdown-toggle" id="footerDropRightMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About</a>
                <div class="dropdown-menu" aria-labelledby="footerDropRight">
                      <a class="dropdown-item" href="/our_story">Our Story</a>
                      <a class="dropdown-item" href="/the_owner">The Owner</a>
                      <a class="dropdown-item" href="/coffeebean">Coffeebeans</a>
                      <a class="dropdown-item" href="/press">Press</a>
                    </div>
              </li>                              
              <li class="footer-list-item"><a class="footer-list-link" href="/gallery">Gallery</a></li> 
              <li class="footer-list-item"><a class="footer-list-link" href="/products">Menu</a></li>
              <li class="footer-list-item"><a class="footer-list-link" href="#">Cart</a></li>
              <%# <li class="footer-list-item"><a class="footer-list-link" href="#">Careers</a></li> %>
              <li class="footer-list-item"><a class="footer-list-link" href="/location">Location</a></li>
              <li class="footer-list-item"><a class="footer-list-link" href="/users/sign_in">Login/Register</a></li>
            </ul>
          <!-- End List -->
          </div>
          
          <div class="col-sm-3 sm-margin-b-30">
            <h3>Follow Us</h3>
            <!-- List -->
            <ul class="list-unstyled footer-list">
              <li class="footer-list-item"><a class="footer-list-link" href="https://www.facebook.com/crowncoffeesg/">Facebook</a></li>
              <li class="footer-list-item"><a class="footer-list-link" href="https://www.instagram.com/crowncoffeesg/">Instagram</a></li>
            </ul>
          <!-- End List -->
          </div>
          <div id="note" class="col-sm-5 sm-margin-b-30">
            <h2>Send Us A Note</h2>     
            <% if @comment && @comment.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being submiited:</h2>
             
                <ul>
                <% @comment.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <% if note %>
              <p class="alert alert-success"><%= note %></p>
            <% end %>
            <%= form_with scope: :comment, url: comments_path, local: true do |form| %>
              <%= form.text_field :name, :class => "form-control footer-input margin-b-20", placeholder: "Name" %>
              <%= form.text_field :email, :class => "form-control footer-input margin-b-20", placeholder: "Email" %>
              <%= form.telephone_field :mobile_number, :class => "form-control footer-input margin-b-20", placeholder: "Mobile Number" %>
              <%= form.text_area :message, :class => "form-control footer-input margin-b-30", placeholder: "Your Message"%>
              <%= form.submit :class => "btn-theme btn-theme-sm btn-base-bg text-uppercase"%>
            <% end %>

          </div>
          <!--// end row -->
        </div>
      </div>
      <!-- End Links -->
    </div>
    <!-- Copyright -->
    <div class="content container">
      <div class="row footer-copyright">
        <div class="col-xs-6 color-white">
          <%= image_tag( "logo.png", class: "footer-logo", alt: "Crown Coffee Logo")%>
        </div>
        <div class="col-xs-6 color-white">
          © 2018 Crown Coffee Pte Ltd. All Rights Reserved.
        </div>
      </div>
      <!--// end row -->
    </div>
    <!-- End Copyright -->
  </footer>


  <%#  JAVASCRIPTS%>
  <%# Core Plugin %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.1/jquery-migrate.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" type="text/javascript"></script>
   <%= javascript_include_tag 'application'%>

  <%# Page Level Plugin %
  <%# <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-smooth-scroll/2.2.0/jquery.smooth-scroll.min.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.2/js/swiper.min.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.1/masonry.pkgd.min.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" type="text/javascript"></script> %>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.1/jquery-migrate.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" type="text/javascript"></script>
    <%= javascript_include_tag 'application'%>
  </body>
</html>